[theme]
primaryColor = "#008080"
backgroundColor = "#000000"
# secondaryBackgroundColor = "#154360"
secondaryBackgroundColor = "#0d1014"
textColor = "#fafafa"
font = "monospace"

[server]
# Enable static file serving
enableStaticServing = true

# Automatically refresh the app when changes are detected
runOnSave = true